# Generated by Django 2.2.10 on 2020-02-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='借用人')),
                ('author', models.CharField(max_length=255, verbose_name='機器型號')),
                ('publisher', models.CharField(max_length=255, verbose_name='設備')),
            ],
        ),
    ]
